rage/python-editor

src/components/Output.tsx, src/components/index.tsx
Modify to get program output when running Skulpt. Add a component to display the output.
=> Add component to show program output

src/components/Output.tsx
Improves output styling using styled-components and Material UI components. Adds sliding animation for showing and hiding the output.
=> Output styling

example/cypress/integration/home_page_spec.js, package-lock.json, package.json, src/components/Output.tsx, src/components/Quiz.tsx, src/components/worker.js
Adds functionality for entering user input and modifies output to auto scroll to last line. An input field is displayed in output when input is requested, and user input is added to the output after pressing enter.
=> User input

example/cypress/integration/home_page_spec.js, src/components/PyEditor.tsx, src/components/Quiz.tsx, src/components/worker.js
Adds a stop button that terminates/stops a running worker and starts a new one to replace it if Skulpt is still running, otherwise stops worker from sending more print messages. 
Modifies worker to send print messages in batches for better performance.
=> Stop worker

example/cypress/integration/home_page_spec.js, now.json, package-lock.json, package.json, src/components/Output.tsx, src/components/Quiz.tsx
Adds stop button and running status to output title box. Additionally, output box opens up every time a program runs, even if it doesn't print anything.
=> Show running status

example/package-lock.json, example/package.json, src/components/PyEditor.tsx, src/components/Quiz.tsx, src/components/QuizLoader.tsx, src/services/import_parsing.ts
This pull request features several small improments to code legibility. In addition, Cypress is updated to version 4.3.0.
=> Code quality

example/cypress/integration/home_page_spec.js, src/components/Output.tsx, src/components/Quiz.tsx, src/components/TestProgressBar.tsx, src/components/TestResults.tsx, src/components/worker.js, src/types.ts
Adds a button for running default tests from web worker, that returns an array containing test results.
Modifies Output to display test results whenever tests have been run. Each result displays test name, pass/fail status and possible feedback. Shows only first failed result by default, and all results can be viewed by checking "Show all" checkbox. Includes a progress bar for displaying percentage of passed tests in the output title.
=> Test results

src/components/Output.tsx, src/components/OutputContent.tsx, src/components/OutputTitle.tsx
Refactors output title and content from component Output to child components OutputTitle and OutputContent.
=> Refactor output

src/components/OutputContent.tsx, src/components/OutputTitle.tsx, src/components/TestProgressBar.tsx
Adds minor improvements to output UI. Slightly modifies colors and grid in output title.
=> Add improvements to UI

src/components/QuizLoader.tsx, src/locales/common/en.json, src/locales/common/fi.json, src/services/quiz.ts, src/types.ts
This feature makes the editor load the state of the exercise during the latest submission at start.
=> Load latest submission

src/components/ProgrammingExerciseLoader.tsx, src/locales/common/en.json, src/locales/common/fi.json
Solves scenarios such as https://github.com/rage/python-s20/issues/14
Fixes #81
=> Logout refresh and error handling for loading exercises

src/components/ProgrammingExercise.tsx, src/components/worker.js, src/hooks/getWorker.tsx
=> Kill worker state

example/cypress/integration/state_integrity.js, src/components/OutputContent.tsx, src/components/OutputTitle.tsx, src/components/ProgrammingExercise.tsx, src/components/PyEditorButtons.tsx, src/types.ts
=> Initial merging of mutually exclusive states

LICENSE, LICENSE-MIT, README.md, example/package.json
=> Add license files and notice

src/components/ProgrammingExercise.tsx, src/components/worker.js
Resolves #104 
Less naive approach for now
=> Remove fstring polyfill, regex input to input(

src/components/worker.js
=> Stack traces

src/components/ProgrammingExercise.tsx, src/components/worker.js, src/locales/common/en.json, src/locales/common/fi.json, src/services/patch_exercise.ts
=> Kill worker after 10 sec when executing and testing code

example/cypress/integration/home_page_spec.js, src/components/ProgrammingExercise.tsx, src/components/ProgrammingExerciseLoader.tsx, src/locales/common/en.json, src/locales/common/fi.json, src/services/patch_exercise.ts
=> Incompatible exercise

src/components/EditorOutput.tsx, src/components/Help.tsx, src/components/ProgrammingExercise.tsx, src/components/ProgrammingExerciseLoader.tsx, src/components/TestOutput.tsx
Improvements to need help. "Closes" #118?
=> Move need help from output header to content

src/components/Notification.tsx, src/components/ProgrammingExerciseLoader.tsx, src/locales/common/en.json, src/locales/common/fi.json, src/services/patch_exercise.ts
=> More incompatibility errors, suggest to contact course instructor

src/components/ProgrammingExerciseLoader.tsx
=> Get exercise details even when not signed in

example/cypress/integration/home_page_spec.js, src/components/EditorOutput.tsx, src/components/OutputBox.tsx, src/components/ProgrammingExercise.tsx, src/components/SubmissionOutput.tsx, src/components/TestOutput.tsx, src/components/TestProgressBar.tsx, src/components/worker.js, src/locales/common/en.json, src/locales/common/fi.json, src/types.ts
=> Show initializing status before worker is ready

README.md, src/components/ProgrammingExerciseLoader.tsx
=> Write proper readme

example/cypress/integration/api_test_spec.js, src/components/ProgrammingExercise.tsx, src/components/ProgrammingExerciseLoader.tsx, src/services/patch_exercise.ts
Resolves #143 
Resolves #145 
Resolves #146
=> Fix load latest submission, auto submission, move model solution button

example/src/index.tsx, src/components/ProgrammingExerciseLoader.tsx
=> Reload exercise when slugs change

example/cypress/fixtures/get_exercise.json, example/cypress/fixtures/get_expired_exercise.json, example/cypress/integration/api_test_spec.js, example/cypress/integration/state_integrity_spec.js, src/components/ProgrammingExerciseLoader.tsx, src/locales/common/en.json, src/locales/common/fi.json, src/services/programming_exercise.ts, src/types.ts
=> Better message when exercise not yet unlocked

src/components/ProgrammingExercise.tsx, src/components/WithBrowserIncompatibilityOverlay.tsx, src/components/worker.js
=> Pyodide 0.17
